2022-04-27 00:45:41.526 | ERROR    | app_doc.views:doc:1073 - 文集浏览出错
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f94a43db510>
    └ <Thread(Thread-110, started daemon 140276147955456)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f94a43db2f0>
    └ <Thread(Thread-110, started daemon 140276147955456)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-110, started daemon 140276147955456)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-110, started daemon 140276147955456)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f949f9b10b8>>
    └ <Thread(Thread-110, started daemon 140276147955456)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 33212)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f949f24abf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f949f9b10b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f949f9b10b8>
    │    │                   │        └ ('127.0.0.1', 33212)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f949f9b10b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f949e248bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f94974e4a20>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f949e248c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f94974e4a20>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f949e248268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f949f9b10b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f94974e4a20>
    │       └ <function BaseHandler.run at 0x7f949e23bf28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f949f99e438>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f949e2442f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f949f99e438>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f949f99e438>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f949cd20c50>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f949f99e438>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler.get_response at 0x7f949e28b488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f949cd20c50>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f94974ecc80>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f949cd20c50>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f949751e5f8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f94974ecbf8>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f949751e5f8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f949752aba8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f94974ecb70>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f949752aba8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f949752abe0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f94974ecae8>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f949752abe0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f949cd3b080>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f94974eca60>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f949cd3b080>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f949c0f8278>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f94974ec9d8>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f949c0f8278>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f949c0f8320>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f94974ec950>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f949c0f8320>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f949c0f83c8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f94974ec8c8>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f949c0f83c8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f949c166128>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f94974ec840>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f949c166128>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f949c166208>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               │    └ <function BaseHandler._get_response at 0x7f9497725ea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f949c166208>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f949cd20c50>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 323}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-323/'>
               └ <function doc at 0x7f9497ff8950>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 323}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-323/'>
           └ <function doc at 0x7f9497ff88c8>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 323
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f949e3511d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 323, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f949f315ae8>
                   └ <django.db.models.manager.Manager object at 0x7f9497595b00>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-04-27 19:43:50.449 | ERROR    | app_doc.views:doc:1073 - 文集浏览出错
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fc1b2bb3510>
    └ <Thread(Thread-224, started daemon 140469653145344)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fc1b2bb32f0>
    └ <Thread(Thread-224, started daemon 140469653145344)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-224, started daemon 140469653145344)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-224, started daemon 140469653145344)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fc1ae1880b8>>
    └ <Thread(Thread-224, started daemon 140469653145344)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 36574)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fc1ada21bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fc1ae1880b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fc1ae1880b8>
    │    │                   │        └ ('127.0.0.1', 36574)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fc1ae1880b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fc1aca1fbf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fc1a5d6c198>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fc1aca1fc80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fc1a5d6c198>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fc1aca1f268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fc1ae1880b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fc1a5d6c198>
    │       └ <function BaseHandler.run at 0x7fc1aca12f28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fc1a47905f8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fc1aca1b2f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fc1a47905f8>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fc1a47905f8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fc1a68b8fd0>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fc1a47905f8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler.get_response at 0x7fc1aca62488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fc1a68b8fd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fc1a5cdbd08>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fc1a68b8fd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fc1a5d103c8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fc1a5cdbc80>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fc1a5d103c8>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fc1a5d10f28>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fc1a5cdbbf8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fc1a5d10f28>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fc1a5d10860>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fc1a5cdbb70>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fc1a5d10860>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fc1a6925f28>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fc1a5cdbae8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fc1a6925f28>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fc1a68c00f0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fc1a5cdba60>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fc1a68c00f0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fc1a68c0208>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fc1a5cdb9d8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fc1a68c0208>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fc1a68c0160>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fc1a5cdb950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fc1a68c0160>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fc1a5d19a58>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fc1a5cdb8c8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fc1a5d19a58>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fc1a5d19198>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler._get_response at 0x7fc1a5ea1f28>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fc1a5d19198>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fc1a68b8fd0>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 343}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <function doc at 0x7fc1a67e5598>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 343}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-343/'>
           └ <function doc at 0x7fc1a67e5510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 1000, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 343
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fc1acb281d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 343, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fc1adaecae8>
                   └ <django.db.models.manager.Manager object at 0x7fc1a5d89b00>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
