2022-03-03 14:05:03.738 | ERROR    | app_doc.views:doc:1070 - 文集浏览出错
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7085956510>
    └ <Thread(Thread-1043, started daemon 140120992794368)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f70859562f0>
    └ <Thread(Thread-1043, started daemon 140120992794368)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1043, started daemon 140120992794368)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1043, started daemon 140120992794368)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>>
    └ <Thread(Thread-1043, started daemon 140120992794368)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 51448)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f70807c6bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
    │    │                   │        └ ('127.0.0.1', 51448)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f707f7c5bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f7076b855c0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f707f7c5c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f7076b855c0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f707f7c5268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f7076b855c0>
    │       └ <function BaseHandler.run at 0x7f707f7baf28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f707621cfd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f707f7c12f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f707621cfd0>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f707621cfd0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f707621cfd0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler.get_response at 0x7f707f807488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91bf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f707cac18d0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91b70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f707cac18d0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f707cac1908>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91ae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f707cac1908>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f707cac1c88>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91a60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f707cac1c88>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f707d672198>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca919d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f707d672198>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f707d672128>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f707d672128>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f707d672160>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca918c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f707d672160>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f707cace6a0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91840>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f707cace6a0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f707cacec18>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca917b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f707cacec18>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f707e369160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler._get_response at 0x7f707caebea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f707e369160>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 343}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <function doc at 0x7f707d599598>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 343}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-343/'>
           └ <function doc at 0x7f707d599510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 997, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 343
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f707f8cc1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 343, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f7080890ae8>
                   └ <django.db.models.manager.Manager object at 0x7f707cb3bac8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-03-03 14:44:37.801 | ERROR    | app_doc.views:doc:1070 - 文集浏览出错
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7085956510>
    └ <Thread(Thread-1090, started daemon 140121014322944)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f70859562f0>
    └ <Thread(Thread-1090, started daemon 140121014322944)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1090, started daemon 140121014322944)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1090, started daemon 140121014322944)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>>
    └ <Thread(Thread-1090, started daemon 140121014322944)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53362)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f70807c6bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
    │    │                   │        └ ('127.0.0.1', 53362)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f707f7c5bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f707cac1be0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f707f7c5c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f707cac1be0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f707f7c5268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f707cac1be0>
    │       └ <function BaseHandler.run at 0x7f707f7baf28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f7074c4c208>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f707f7c12f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f7074c4c208>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f7074c4c208>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f7074c4c208>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │    └ <function BaseHandler.get_response at 0x7f707f807488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-777/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91bf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f707cac18d0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91b70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f707cac18d0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f707cac1908>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91ae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f707cac1908>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f707cac1c88>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91a60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f707cac1c88>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f707d672198>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca919d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f707d672198>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f707d672128>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f707d672128>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f707d672160>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca918c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f707d672160>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f707cace6a0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91840>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f707cace6a0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f707cacec18>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca917b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f707cacec18>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f707e369160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               │    └ <function BaseHandler._get_response at 0x7f707caebea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f707e369160>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 777}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-777/'>
               └ <function doc at 0x7f707d599598>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 777}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-777/'>
           └ <function doc at 0x7f707d599510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 997, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 777
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f707f8cc1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 777, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f7080890ae8>
                   └ <django.db.models.manager.Manager object at 0x7f707cb3bac8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2022-03-04 00:04:45.918 | ERROR    | app_doc.views:doc:1070 - Collection browsing error
Traceback (most recent call last):
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7085956510>
    └ <Thread(Thread-1286, started daemon 140121004095232)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f70859562f0>
    └ <Thread(Thread-1286, started daemon 140121004095232)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1286, started daemon 140121004095232)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1286, started daemon 140121004095232)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>>
    └ <Thread(Thread-1286, started daemon 140121004095232)>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 40590)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7f70807c6bf8>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
    │    │                   │        └ ('127.0.0.1', 40590)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f707f7c5bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f70762ba550>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f707f7c5c80>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f70762ba550>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7f707f7c5268>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7f7080f2c0b8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7f70762ba550>
    │       └ <function BaseHandler.run at 0x7f707f7baf28>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f7076b00eb8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7f707f7c12f0>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7f7076b00eb8>
    │    │        │           │    └ {'LC_ALL': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7f7076b00eb8>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7f7076b00eb8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler.get_response at 0x7f707f807488>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91bf8>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7f707cac18d0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91b70>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7f707cac18d0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f707cac1908>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91ae8>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7f707cac1908>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7f707cac1c88>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91a60>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7f707cac1c88>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7f707d672198>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca919d8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7f707d672198>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f707d672128>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91950>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7f707d672128>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f707d672160>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca918c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7f707d672160>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f707cace6a0>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca91840>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7f707cace6a0>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f707cacec18>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7f707ca917b8>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7f707cacec18>
               └ None
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f707e369160>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 35, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               │    └ <function BaseHandler._get_response at 0x7f707caebea0>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7f707e369160>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f707d6d8f60>>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 21, 'doc_id': 343}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-21/doc-343/'>
               └ <function doc at 0x7f707d599598>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 21, 'doc_id': 343}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-21/doc-343/'>
           └ <function doc at 0x7f707d599510>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 997, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 343
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7f707f8cc1d0>
          └ <class 'app_doc.models.Doc'>

  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 343, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7f7080890ae8>
                   └ <django.db.models.manager.Manager object at 0x7f707cb3bac8>
  File "/www/server/python_manager/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
