2021-08-02 10:07:50.020 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.920087.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.920087.png?",)
2021-08-02 10:07:50.038 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9310026.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9310026.png?",)
2021-08-02 10:07:50.049 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9280918.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9280918.png?",)
2021-08-02 10:07:50.060 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9331753.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9331753.png?",)
2021-08-02 10:07:50.091 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9356186.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9356186.png?",)
2021-08-02 10:07:50.128 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9376152.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9376152.png?",)
2021-08-02 10:07:50.152 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.955394.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.955394.png?",)
2021-08-02 10:07:50.163 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.957492.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.957492.png?",)
2021-08-02 10:07:50.209 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9592867.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9592867.png?",)
2021-08-02 10:07:50.240 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1646230.6237563968401273.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1646230.6237563968401273.png?",)
2021-08-02 10:07:50.251 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1728480.2817707048990693.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1728480.2817707048990693.png?",)
2021-08-02 10:07:50.264 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1737530.30787306714992335.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1737530.30787306714992335.png?",)
2021-08-02 10:07:50.276 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1750410.7020816132164583.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1750410.7020816132164583.png?",)
2021-08-02 10:07:51.007 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9487813.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9487813.png?",)
2021-08-02 10:07:51.022 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9527805.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9527805.png?",)
2021-08-02 10:07:51.036 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9469712.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9469712.png?",)
2021-08-02 10:07:51.047 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9237013.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9237013.png?",)
2021-08-02 10:07:51.060 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9263947.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9263947.png?",)
2021-08-02 10:07:51.071 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9396784.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9396784.png?",)
2021-08-02 10:07:51.083 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9425926.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9425926.png?",)
2021-08-02 10:07:51.093 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9448943.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9448943.png?",)
2021-08-02 10:20:37.023 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.920087.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.920087.png?",)
2021-08-02 10:20:37.038 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9425926.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9425926.png?",)
2021-08-02 10:20:37.050 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9396784.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9396784.png?",)
2021-08-02 10:20:37.062 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9280918.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9280918.png?",)
2021-08-02 10:20:37.074 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9310026.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9310026.png?",)
2021-08-02 10:20:37.085 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9331753.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9331753.png?",)
2021-08-02 10:20:37.096 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9356186.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9356186.png?",)
2021-08-02 10:20:37.108 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9376152.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9376152.png?",)
2021-08-02 10:20:37.120 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9448943.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9448943.png?",)
2021-08-02 10:20:37.131 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.955394.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.955394.png?",)
2021-08-02 10:20:37.144 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.957492.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.957492.png?",)
2021-08-02 10:20:37.157 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9237013.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9237013.png?",)
2021-08-02 10:20:37.167 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1737530.30787306714992335.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1737530.30787306714992335.png?",)
2021-08-02 10:20:38.017 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1728480.2817707048990693.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1728480.2817707048990693.png?",)
2021-08-02 10:20:38.033 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9527805.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9527805.png?",)
2021-08-02 10:20:38.052 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9592867.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9592867.png?",)
2021-08-02 10:20:38.064 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1646230.6237563968401273.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1646230.6237563968401273.png?",)
2021-08-02 10:20:38.077 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1750410.7020816132164583.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1750410.7020816132164583.png?",)
2021-08-02 10:20:38.089 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9263947.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9263947.png?",)
2021-08-02 10:20:38.100 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9469712.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9469712.png?",)
2021-08-02 10:20:38.111 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9487813.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9487813.png?",)
2021-08-02 10:20:38.122 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-02_1016450.034139424210533065.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-02_1016450.034139424210533065.png?",)
2021-08-02 10:20:38.136 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-02_1017140.003877683336248383.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-02_1017140.003877683336248383.png?",)
2021-08-02 10:28:07.184 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.920087.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.920087.png?",)
2021-08-02 10:28:07.201 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9376152.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9376152.png?",)
2021-08-02 10:28:07.213 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9356186.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9356186.png?",)
2021-08-02 10:28:07.225 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-02_1017140.003877683336248383.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-02_1017140.003877683336248383.png?",)
2021-08-02 10:28:07.237 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9592867.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9592867.png?",)
2021-08-02 10:28:07.249 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.957492.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.957492.png?",)
2021-08-02 10:28:07.260 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1646230.6237563968401273.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1646230.6237563968401273.png?",)
2021-08-02 10:28:07.272 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1728480.2817707048990693.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1728480.2817707048990693.png?",)
2021-08-02 10:28:07.285 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1737530.30787306714992335.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1737530.30787306714992335.png?",)
2021-08-02 10:28:07.297 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-01_1750410.7020816132164583.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-01_1750410.7020816132164583.png?",)
2021-08-02 10:28:07.312 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-02_1016450.034139424210533065.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-02_1016450.034139424210533065.png?",)
2021-08-02 10:28:07.325 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9237013.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9237013.png?",)
2021-08-02 10:28:07.336 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9396784.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9396784.png?",)
2021-08-02 10:28:08.170 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9310026.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9310026.png?",)
2021-08-02 10:28:08.181 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9331753.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9331753.png?",)
2021-08-02 10:28:08.194 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9425926.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9425926.png?",)
2021-08-02 10:28:08.209 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9448943.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9448943.png?",)
2021-08-02 10:28:08.224 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9469712.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9469712.png?",)
2021-08-02 10:28:08.239 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9487813.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9487813.png?",)
2021-08-02 10:28:08.255 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9527805.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9527805.png?",)
2021-08-02 10:28:08.271 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.955394.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.955394.png?",)
2021-08-02 10:28:08.321 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9280918.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9280918.png?",)
2021-08-02 10:28:08.339 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202105//1621914616.9263947.png': No schema supplied. Perhaps you meant http:///media/202105//1621914616.9263947.png?",)
2021-08-02 15:35:26.495 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb1cd381378>
    └ <Thread(Thread-1584, started daemon 140401105155840)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb1cd381158>
    └ <Thread(Thread-1584, started daemon 140401105155840)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1584, started daemon 140401105155840)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1584, started daemon 140401105155840)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>>
    └ <Thread(Thread-1584, started daemon 140401105155840)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 5800)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb1c6f38e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │    │                   │        └ ('127.0.0.1', 5800)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb1c5fe4b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1c56f2550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb1c5fe4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1c56f2550>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb1c5fe40d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1c56f2550>
    │       └ <function BaseHandler.run at 0x7fb1c5fdbd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6e10>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb1c5fe1158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6e10>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6e10>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd8b6e10>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler.get_response at 0x7fb1c616b840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf2f0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf7b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf840>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf29cf28>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               │    └ <function BaseHandler._get_response at 0x7fb1bf29c730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 22, 'doc_id': 53}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-22/doc-53/'>
               └ <function doc at 0x7fb1c4036048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 22, 'doc_id': 53}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-22/doc-53/'>
           └ <function doc at 0x7fb1c4033f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 53
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb1c60f5048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 53, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb1c70008c8>
                   └ <django.db.models.manager.Manager object at 0x7fb1bf35a208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
2021-08-02 17:29:52.710 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-02_1647200.28581888628803354.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-02_1647200.28581888628803354.png?",)
2021-08-02 17:30:27.163 | ERROR    | app_doc.util_upload_img:url_img_upload:288 - 上传URL图片异常：MissingSchema("Invalid URL '/media/202108/2021-08-02_1647200.28581888628803354.png': No schema supplied. Perhaps you meant http:///media/202108/2021-08-02_1647200.28581888628803354.png?",)
2021-08-02 17:55:26.090 | ERROR    | app_doc.views:doc:1022 - 文集浏览出错
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb1cd381378>
    └ <Thread(Thread-1676, started daemon 140401105155840)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb1cd381158>
    └ <Thread(Thread-1676, started daemon 140401105155840)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1676, started daemon 140401105155840)>
    │    │        │    └ (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('...
    │    │        └ <Thread(Thread-1676, started daemon 140401105155840)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>>
    └ <Thread(Thread-1676, started daemon 140401105155840)>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 6146)
    │    │              └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <function BaseServer.finish_request at 0x7fb1c6f38e18>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │    │                   │        └ ('127.0.0.1', 6146)
    │    │                   └ <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 9200), raddr=('1...
    │    └ <class 'django.core.servers.basehttp.WSGIRequestHandler'>
    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb1c5fe4b70>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bc5411d0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fb1c5fe4bf8>
    └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bc5411d0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
    │       │   │    │      └ <function WSGIServer.get_app at 0x7fb1c5fe40d0>
    │       │   │    └ <django.core.servers.basehttp.WSGIServer object at 0x7fb1c742beb8>
    │       │   └ <django.core.servers.basehttp.WSGIRequestHandler object at 0x7fb1bc5411d0>
    │       └ <function BaseHandler.run at 0x7fb1c5fdbd90>
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd7321d0>
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
    │    │        │           │    │        │    └ <function BaseHandler.start_response at 0x7fb1c5fe1158>
    │    │        │           │    │        └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd7321d0>
    │    │        │           │    └ {'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'PWD': '/', 'LANG': 'en_US.UTF-8', 'SHLVL': '1', '_': '/usr/bin...
    │    │        │           └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd7321d0>
    │    │        └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
    │    └ None
    └ <django.core.servers.basehttp.ServerHandler object at 0x7fb1bd7321d0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler.get_response at 0x7fb1c616b840>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
               │    │                 └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf2f0>
               └ <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf158>
               │           └ <django.middleware.security.SecurityMiddleware object at 0x7fb1bf2ded30>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf048>
               │           └ <django.contrib.sessions.middleware.SessionMiddleware object at 0x7fb1bf2ecfd0>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf730>
               │           └ <django.middleware.locale.LocaleMiddleware object at 0x7fb1bf2ec160>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf7b8>
               │           └ <django.middleware.common.CommonMiddleware object at 0x7fb1c41ddf60>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf840>
               │           └ <django.middleware.csrf.CsrfViewMiddleware object at 0x7fb1c418e860>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf8c8>
               │           └ <django.contrib.auth.middleware.AuthenticationMiddleware object at 0x7fb1c418e908>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf2bf950>
               │           └ <django.contrib.messages.middleware.MessageMiddleware object at 0x7fb1c418e748>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
               │           │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │           │    └ <function convert_exception_to_response.<locals>.inner at 0x7fb1bf29cf28>
               │           └ <django.middleware.clickjacking.XFrameOptionsMiddleware object at 0x7fb1bf2f7a20>
               └ None
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/app_admin/middleware/require_login_middleware.py", line 33, in __call__
    response = self.get_response(request)
               │    │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               │    └ <function BaseHandler._get_response at 0x7fb1bf29c730>
               └ <app_admin.middleware.require_login_middleware.RequiredLoginMiddleware object at 0x7fb1bf2f7e48>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
               │            └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7fb1c49dcb38>>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               │                │         │                └ {'pro_id': 1, 'doc_id': 161}
               │                │         └ ()
               │                └ <WSGIRequest: GET '/project-1/doc-161/'>
               └ <function doc at 0x7fb1c4036048>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
           │    │         │       └ {'pro_id': 1, 'doc_id': 161}
           │    │         └ ()
           │    └ <WSGIRequest: GET '/project-1/doc-161/'>
           └ <function doc at 0x7fb1c4033f28>

> File "/usr/local/projects/MrDoc/app_doc/views.py", line 949, in doc
    doc = Doc.objects.get(id=int(doc_id),status__in=[0,1]) # 文档信息
          │   │                  └ 161
          │   └ <django.db.models.manager.ManagerDescriptor object at 0x7fb1c60f5048>
          └ <class 'app_doc.models.Doc'>

  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   │    │               │      │       └ {'id': 161, 'status__in': [0, 1]}
                   │    │               │      └ ()
                   │    │               └ 'get'
                   │    └ <function BaseManager.get_queryset at 0x7fb1c70008c8>
                   └ <django.db.models.manager.Manager object at 0x7fb1bf35a208>
  File "/usr/local/projects/MrDoc/MrDoc_venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
    │    │     │     └ 'Doc'
    │    │     └ <Options for Doc>
    │    └ <class 'app_doc.models.Doc'>
    └ <QuerySet [<Doc: About>, <Doc: 1、算法框架>, <Doc: 1、TDH>, <Doc: 1.1 常用方法>, <Doc: 2、Shell>, <Doc: 2.1 常用命令>, <Doc: 2.2 示例脚本>, <Doc...

app_doc.models.Doc.DoesNotExist: Doc matching query does not exist.
